servers:
  master:
    - protocol: http
      url: "https://master1.ddnet.tw/ddnet/15/servers.json"
      refresh_cooldown: 10

    # - protocol: http
    #   url: "https://master2.ddnet.tw/ddnet/15/servers.json"
    #   refresh_cooldown: 10
    
    - protocol: udp
      host: "master1.teeworlds.com"
      port: 8283
      refresh_cooldown: 15
    
    - protocol: udp
      host: "master2.teeworlds.com"
      port: 8283
      refresh_cooldown: 15
